language: ruby

before_script:
- cp config/database.yml.travis config/database.yml
- mysql -e "create database IF NOT EXISTS TEMDF_test;" -uroot
- export MAILGUN_API_KEY="secret"
- rake db:migrate RAILS_ENV=test

script: 
  - rake test

rvm:
- 2.2.0

notifications:
  email:
    recipients:
    - ebenezer.andrade1@gmail.com

branches:
  only:
  - master
  - development
